name: passage_flex_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: id.passage.passage_flex_flutter
        pluginClass: PassageFlutterPlugin
      ios:
        pluginClass: PassageFlutterPlugin
      web:
        pluginClass: PassageFlutterWeb
        fileName: passage_flutter_web.dart
